FROM  evahamrud/sc_multi_omic-archr:latest

LABEL authors="eva.hamrud@crick.ac.uk" \
      description="Docker image with extras"

RUN   python3 -m ensurepip --default-pip
RUN   python3 -m pip install MACS2