FROM  evahamrud/sc_multi_omic-archr_r4.1.2:latest

LABEL authors="eva.hamrud@crick.ac.uk" \
      description="Docker image with R4.1.2 and ArchR plus extras"

RUN   R -e "install.packages('future.apply')" 